name: SSH into Windows Server and run git pull
on:
  push:
    branches:
      - main # Change this to your branch name
 
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Execute remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd C:\inetpub\hello-world
            git pull
